{
    "name": "Deployed server config",
    "comment": "This config is used for launching the server",
    "data_prefix": "/home/ubuntu/cb2-game-data",
    "card_covers": true,
    "fog_start": 13,
    "fog_end": 20,
    "google_oauth_client_id": "787231947800-ee2g4lptmfa0av2qb26n1qu60hf5j2fd.apps.googleusercontent.com",
    "map_config": {
      "streetlight_tiles": ["GROUND_TILE_STREETLIGHT"]
    }
}
